### ISSUE TITLE
Lower API requirement to 1.13.0

### ISSUE THREAD

**Issue by danielreuther** [midwan/MB_SubSonic#13]
Because of the recent move of Subsonic away from its open source roots, it looks like forks gained some traction. The things being worked on over at the LibreSonic project, for instance, look promising.

But these are stuck with the API version that's been shipped with the last GPL-licensed Subsonic version (which is 1.13.0).

Is there anything in particular the plugin would require 1.14.0 for? Would you consider lowering the requirement?

Thanks!

**Comment by midwan** [comment]
I wasn't aware of this development, thanks from bringing it to my attention.
We can certainly lower the API requirement, if 1.13.0 works then it's easy. :)

**Comment by midwan** [comment]
Just pushed a commit that fixes this, the binaries will follow soon.

**Comment by danielreuther** [comment]
Great, thanks much! I can confirm that my 5.3 instance is answering the requests now -- alas, I'm now running into https://github.com/midwan/MB_SubSonic/issues/14
