### ISSUE TITLE
Unable to connect to server (other subsonic clients work fine)

### ISSUE THREAD

**Issue by nish81** [midwan/MB_SubSonic#17]
(I'm completely rewriting this post 9 mins after posting it as I did some more digging and found a lot more relevant information)

I've set up Ampache on a server and configured the Subsonic API to work there. Unfortunately it only implements version 1.11.0 of the API and there appear to be no immediate plans to upgrade this.

I've been able to connect to it and successfully play music using an old version of dSub installed on my Android phone (I think if I update it to the newest version it'll fail as I've read reports of this happening). I've also been able to successfully connect to it using the latest version of Subclient on Windows (and play music etc).

However, if I use the MusicBee plugin (my preferred player!) I get the error message that the REST API is too old and the server must update. This is when attempting to connect to the server, so I cannot see any songs at all. Ie the authentication itself doesn't seem to work? 

Now I went into my Ampache's installation folder and changed the version that it broadcasts. Ie I edited /lib/class/subsonic_xml_data.class.php and changed the constant from '... 1.11.0' to '... 1.13.0' just to see what would happen. The results are:

dSub and Subclient still both work fully (can browse and play music).

MusicBee: now connects and can browse music. I see all my songs (24, just to test it out), with album art etc. However, only two of them play successfully: a track called 'Harmony' and a track called 'Lycanthrope'. If I try to play any of the others, it tells me 'Error: the source file for track 'Harmony' could not be found' if Harmony is the song I most recently played, and 'Error: the source file for track 'Lycanthrope' could not be found' if Lycanthrope is the song I most recently played. That is, the error references the most recent song successfully played and not the song I'm trying to play.

I'm not sure what this means or why this is the case. Is there any way MusicBee could be compatible with v1.11.0 of the API, since just editing the constant seems to enable browsing and very limited playing functionality?

**Comment by midwan** [comment]
What version is your server?

The plugin has a minimum required version it expects (specifically, it supports a minimum of API v1.13), if yours is older than that it may be why you're getting this message.

It used to be API 1.14 it expected, but we recently lowered that to 1.13 to support Ampache installations with Hex encoded passwords. So it does work with Ampache in general. :)

**Comment by nish81** [comment]
Thanks for the reply midwan! I completely rewrote my original post because I did some digging. The answers to your question, and some more information, are in there. The latest Ampache uses v1.11.0 of the API so I guess it isn't compatible with Ampache in general?

**Comment by midwan** [comment]
I've just pushed an update, to lower the API requirement to 1.11. This should enable it to work on Ampache installations like yours, without too much trouble.

I'll upload the binary in a bit, please let me know if you have any problems with it after that.

**Comment by nish81** [comment]
Thank you! I'll try it out in a bit after you upload the binary.

**Comment by nish81** [comment]
I just tried the new binary, but I have the same set of issues I described in my original post after I lowered the reported API version to 1.11.0. I'll copy paste it again, this is what happens:

MusicBee: now connects and can browse music. I see all my songs (24, just to test it out), with album art etc. However, only two of them play successfully: a track called 'Harmony' and a track called 'Lycanthrope'. If I try to play any of the others, it tells me 'Error: the source file for track 'Harmony' could not be found' if Harmony is the song I most recently played, and 'Error: the source file for track 'Lycanthrope' could not be found' if Lycanthrope is the song I most recently played. That is, the error references the most recent song successfully played and not the song I'm trying to play.

**Comment by midwan** [comment]
Hmm, could you open an account for me to test remotely on your server? If so, please send me the details via e-mail at midwan at gmail dot com, maybe I can see something from here.

**Comment by midwan** [comment]
Ok, I can recreate the problem from here, on your server.
It has something to do with the reported directory structure to files, so I will consider it a bug.
I've flagged the issue as such, and I'll start working on a fix.

If it's not a problem, I would like to request that you leave the account active for a bit more, until we can resolve this. Since I can't recreate it on my server, it would help.

**Comment by nish81** [comment]
Sure, I'll leave it open until you're done, and thank you for the fast work! If there's anything I can do to help let me know.

The actual directory structure is /[Artist]/[Album]/song name.mp3. It all lives in a /music/ folder.

**Comment by midwan** [comment]
Regarding the API requirement, v1.11 does not support Token based authentication which was introduced in v1.13 onwards.

Therefore, the API version information passed from the plugin will have to automatically change depending on the method of authentication selected:
- If HexPass is selected, the plugin will use v1.11 when connecting to the server.
- Otherwise, it will default to v1.13 (to enable Token based authentication).

**Comment by nish81** [comment]
Makes sense. This is separate from the folder structure bug, right?

**Comment by midwan** [comment]
Yes, it's a separate thing. I've already pushed a commit to implement the above behavior, the note was put there for future reference. :)

**Comment by midwan** [comment]
@nish81 
Could you please check if the latest binary helps in this issue or not?
Thanks!

**Comment by midwan** [comment]
@nish81 
Ping!
