### ISSUE TITLE
Ability to listen to podcasts?

### ISSUE THREAD

**Issue by kkuhle** [midwan/MB_SubSonic#25]
@midwan 

I was wondering if there is a way to listen to podcasts that I have on my libresonic.  If not, would this be possible to implement?

**Comment by midwan** [comment]
@kkuhle 
It should be possible, I'll look into it and update this area with news.

**Comment by kkuhle** [comment]
@midwan
That would be incredible!

**Comment by midwan** [comment]
We need some documentation from MusicBee's side to implement this, so I've asked Steven for that:
https://getmusicbee.com/forum/index.php?topic=1972.msg155207#msg155207

**Comment by midwan** [comment]
@kkuhle 
Steven will be looking into this over the next few weeks, so we'll have to wait until there's support for it through MusicBee's API.

**Comment by midwan** [comment]
@kkuhle 
Unfortunately it looks like this won't be happening, as Steven is not willing to implement the necessary support for it.
https://getmusicbee.com/forum/index.php?topic=1972.285

Closing this for now, unless something changes in the future.
