### ISSUE TITLE
Unsupported format or corrupted...

### ISSUE THREAD

**Issue by TheMax2000** [midwan/MB_SubSonic#26]
I have trouble to get the plugin working.
I do see files, but whenever I try to play one, I got the error: "Unable to play this file - it has an unsupported format or is corrupted".
I've tried enabling / disabling transcoding on the server, but it doesn't seem to change anything.
When trying to enable transcoding from the plugin, it doesn't seem to keep the setting.
Any idea of what's going wrong?
My files are not corrupted 'cause I can read them from JamStash.
Thanks for your help!

Edit: Forgot to mention I've tried with mp3 and wma files, neither work. And I'm using v2.2

**Comment by TheMax2000** [comment]
Ok, issue resolved... just updated to 2.11 (!!)
Maybe you should update this page --> http://musicbee.wikia.com/wiki/Subsonic_Client
(I'll let you close the issue once the page is updated ;) )

**Comment by midwan** [comment]
@TheMax2000 
I've updated the wikia page to link to the latest version always... :)
