### ISSUE TITLE
Not showing playlists 

### ISSUE THREAD

**Issue by andocromn** [midwan/MB_SubSonic#27]
I just setup Musicbee and subsonic on a new PC.  For some reason it is not seeing any of the playlists from the subsonic server.  Otherwise seems to be working normally

**Comment by andocromn** [comment]
Did some more testing.  this problem exists in musicbee version 3.1.644 but works fine if I revert musicbee to 3.0.6132.  looks like something must have changed between 3.0 and 3.1.  I have no problem using 3.0 but probably something to look into for the next release

**Comment by midwan** [comment]
@andocromn 
Thanks for letting me know...

I'll take a look as soon as I can and get back to you.

**Comment by midwan** [comment]
This was a bug in MusicBee, which a new binary fixes.

**Comment by jalabulajunx** [comment]
@andocromn - Please check this thread for more information - https://getmusicbee.com/forum/index.php?topic=3620.msg144745#msg144745
