### ISSUE TITLE
I got a hint that it was working, and then nothing.

### ISSUE THREAD

**Issue by Phrenzy** [midwan/MB_SubSonic#29]
I'm running subsonic 6.1.3 on Ubuntu 16.04 and openjdk-8-jre. I'm running MusicBee 3.1.6590 and MB_SubSonic 2.11 on Windows 10. I can connect to SubSonic using Android and iOS clients as well as Jamstash on my Win10 machine. 

I have tried connecting using the server's IP as well as the local DNS name and the external DNS name. (I have an internal DNS domain.) I have tried using HTTP and HTTPS using the standard ports: 80, 443, 4040, 4443. 

Using incorrect usernames and passwords, I have seen MusicBee errors that have the expected information. Bad password and stuff like that, so it appears that MusicBee does see the server.

I am currently using the hostname of the server (subsonic) and the port of 4443, matching exactly the settings I have in Jamstach. 

When I make a change to the subsonic v2.11 settings and click 'apply' I see the words 'Detected a Subsonic server' in the lower left hand corner. I have left it in that state overnight and it remained that way. It will stay like that until I open the preferences tab again. I have about 25,000 songs.

Earlier I did get a hopeful flash of inspiration. I say for the briefest of moments, one of my 'A' artists and ten of their songs. But alas, I have seen nothing since. Any insight you could give would be helpful. Oh yeah, turning off the Win10 firewall does nothing. 

One more thing, soon after seeing those 10 songs, I did see a lot of network traffic coming into my Win10 machine. I took a look around, but I can't see any noteworthy files in my AppData folders.

**Comment by midwan** [comment]
@Phrenzy 
Thanks for the report.
Are you testing this locally, as in your MusicBee installation is in the same LAN as your Subsonic server?

**Comment by Phrenzy** [comment]
Yes.

**Comment by Phrenzy** [comment]
Never mind. Thanks anyway.

**Comment by midwan** [comment]
@Phrenzy 
Did you get it resolved?
I couldn't test this yet because my server was offline until very recently, so I was planning to do more this weekend actually...

**Comment by Phrenzy** [comment]
No.

Dave Ballard

________________________________

**Comment by Phrenzy** [comment]
Thank you for the help. I got it working. I may have been expecting a more direct indication that MusicBee had seen my songs.
