### ISSUE TITLE
Songs displayed as folders

### ISSUE THREAD

**Issue by Koenvh1** [midwan/MB_SubSonic#30]
I noticed that songs themselves are also displayed as subfolders for an album. An example from the Subsonic demo server can be seen here:
![image](https://user-images.githubusercontent.com/5168825/36753443-74425df8-1c06-11e8-90f3-35218a82d1ab.png)

To Turn Around is a song that belongs to the album Plastic City, but also shows up as folder in the library. Could it be that it checks for the existence of the `isDir` attribute rather than the value of it?

**Comment by midwan** [comment]
@Koenvh1 
Thanks for reporting this. I'll try to recreate it now that my server is back online (hasn't been working for quite a while) and get back to you.

**Comment by Koenvh1** [comment]
You seem to miss an isDir check in the GetFolders function:
https://github.com/midwan/MB_SubSonic/blob/master/MB_SubSonic/Subsonic.cs#L307

With that in place it does work as expected:
![afbeelding](https://user-images.githubusercontent.com/5168825/36800053-dcbf98c0-1cae-11e8-904b-0b1b16ae5b89.png)

**Comment by midwan** [comment]
Thanks for the PR, merged! :)

I'll get a new release prepared as soon as I check everything.
