### ISSUE TITLE
'Transcode to MP3' tickbox not saving

### ISSUE THREAD

**Issue by st4rts0mething** [midwan/MB_SubSonic#32]
Auto-explanatory. I try checking that box so I save a bit of bandwidth but the setting apparently can't be saved / applied. Tried using a specific mp3-limited user but for some reason it still streams flac. Am I doing anything wrong? Trying to have musicbee + this as my daily driver, so far so good for streaming flacs.

**Comment by midwan** [comment]
@st4rts0mething 
Thanks for the report, I'll start by trying to recreate this... Perhaps I missed something and it doesn't save that option ;)
