### ISSUE TITLE
'Music' directory on Synology NAS access error

### ISSUE THREAD

**Issue by krilok** [midwan/MB_SubSonic#33]
I have installed and configured both the app on my NAS and the plugin on Musicbee. It's working fine, and the Subsonic folder tree shows all the music folders on my NAS in this order: Subsonic / Music / and then the rest of music folders.

I can individually play tracks without problem, but if I want to simply randomise or shuffle tracks from all folders, right clicking on the 'Subsonic' parent folder and selecting 'Play Shuffled' does actually nothing, and right clicking on the child 'Music' folder throws an error popup with the following warning: ''Error from Subsonic server - An error has occurred: Access denied to file /volume1''.

I have checked all folder and user/group permissions on my NAS, but can't seem to get around this error... Any help would be much appreciated.

I'm attaching a screenshot of the error when selecting the 'Music' folder...
![music folder error](https://user-images.githubusercontent.com/38211404/38494454-e1fa09de-3bed-11e8-99e7-5234803251a5.png)

**Comment by midwan** [comment]
@krilok 
So this pops up as soon as you right click on the Music subfolder, or after you select something from the popup menu?

**Comment by krilok** [comment]
Hi, Midwan. Firstly, thanks for replying...

This warning pops up if I **LEFT** click on the 'Music' folder. If I right click on it instead, I get the MusicBee popup menu, but whatever I may select has no effect/action...

**Comment by midwan** [comment]
@krilok 
Interesting... Does it also happen if you left click on a subfolder below Music, like a specific album from what I see in the screenshot? Or do you get the files showing then?

**Comment by krilok** [comment]
No, it only happens on the Music folder... If I left click on any of the folders below, there's no error warnings, the tracks in that particular folder are displayed and everything can be played fine. If I right click in any of those folders, the MB options work, too...

**Comment by krilok** [comment]
Yes, it is indeed accessible. I use an app called BubbleUPNP on my Android phone to access the music on the NAS over the Internet. The server settings on this app are exactly the same as configured on your plugin, only set to a different port...

**Comment by krilok** [comment]
Forgot to mention; I've also configured the 'Ultrasonic' app on my phone with the same settings and it works fine, too...

**Comment by pbanj** [comment]
im getting the same issue. im using a raspberrypi running dietpi and running airsonic. it used to be fine but now when i try to use it i get the same issue.

**Comment by midwan** [comment]
@pbanj 
Could you provide detailed steps to recreate this please?
I could set up a DietPi installation to test it, perhaps that will show me something.

**Comment by pbanj** [comment]
So it used to work just fine but recently I had to reinstall Windows, so I had to reinstall musicbee and this plugin. I even tried changing folder perms and reinstalling Airsonic, but neither helped. Dsub on Android is fine though. Now on how to it happens. Click anything on the left side browser so let's just say you click the subsonic directory, then try and click any of the artists that show up in the middle.

https://cdn.discordapp.com/attachments/399670410565910529/627623943523794994/unknown.png

https://cdn.discordapp.com/attachments/399670410565910529/627624043566333952/unknown.png

Or let's say you click on an artist on the left side and then try and click on an album in the middle.
https://cdn.discordapp.com/attachments/399670410565910529/627624735181897728/unknown.png

https://cdn.discordapp.com/attachments/399670410565910529/627625312825507879/unknown.png
Same issue.

Now if you click an album on the left side and then a song it works perfectly fine.
https://cdn.discordapp.com/attachments/399670410565910529/627625530749091861/unknown.png

https://cdn.discordapp.com/attachments/399670410565910529/627625620360134705/unknown.png

**Comment by viclangemaire** [comment]
I have the same issue like @pbanj described.

**Comment by jaredallard** [comment]
Also running into this same issue, but I'm unable to play any music at all.

![image](https://user-images.githubusercontent.com/2391349/72397588-31e1f200-36f5-11ea-844d-58ae7fe5a2c7.png)

**Comment by Wmartin417** [comment]
I have this same issue.

**Comment by midwan** [comment]
Unfortunately, so far I haven't had an environment here that would show me this, so I can recreate and fix it.
I'll try setting one up from scratch, in case I get lucky.

@jaredallard 
Could you please share your environment details? What server are you using, version, etc.

**Comment by Wmartin417** [comment]
Airsonic v10.6.2 from ghcr.io/linuxserver/airsonic docker images ran on Debian 10 home server with docker v20.10.2.
Installed v3.3 MusicBee (not portable version) and mb_Subsonic_v2.28 on Windows 10
Plugin is configured to access the server locally and ping responds normally. 
I have set up the plugin to access it over the internet, but seem to get the same error.

I have 1,000+ songs and when refreshed it only retrieves 1 song per album. However, when I access the playlists that I have made on airsonic, the plugin seems to work just fine without giving me an error. I have tried installing the portable version of MusicBee and changing the music directory, but that doesn't seem to be the issue.

Checked the logs for airsonic and doesn't seem to be giving any output when MusicBee gives me the error. If you need any more info, let me know.

**Comment by midwan** [comment]
@Wmartin417 
Thanks, I've finally been able to recreate this on a docker instance, so I'll get it fixed now.

**Comment by pbanj** [comment]
Damn, I was thinking we'd never see this get fixed. Glad you were able to recreate it. What did it end up being?

**Comment by midwan** [comment]
It seems it only happens if you have only 1 root folder (the default "Music" folder) which has the id = 0.
In all my earlier tests I had multiple folders configured, and each one had a separate id, so perhaps that's why I never saw it happen to me. With this new installation I just dumped everything under "Music" to quickly see how it looks, and I could recreate the problem immediately.

The subfolders do show up eventually (after the background task finishes going through them), and I can still play music from there. It's only the root folder that has this problem.

So I'm thinking of checking if there is only one root folder configured, with the id = 0, then just skip that and show the indexes below it right away. I need to refresh my memory about how it all works internally first, been a while since I worked on it. :)

**Comment by zachminot** [comment]
Do you think this is also causing the music to not all show up when I click
on my share with 1 folder? I can only access the songs through going
through the folders in the folder explorer of music bee, where as I'd want
to see them in the details pane all at once.

**Comment by midwan** [comment]
Possibly. I think I might end up doing a big rewrite internally, as I don't really like the way it's designed - this was "inherited" from the original design that I picked up, when I decided to help move this project forward.
I'll probably spend some time on it during the weekend, stay tuned. :)

**Comment by midwan** [comment]
This should be fixed now, with the new release: https://github.com/midwan/MB_SubSonic/releases/tag/v2.30

Please let me know if you still have any issues, I only had time for limited testing here, but it seems to work as expected now.
