### ISSUE TITLE
Configuration not being saved

### ISSUE THREAD

**Issue by ajmcateer** [midwan/MB_SubSonic#36]
I have a fresh install of the latest MusicBee client(3.1.6590), and a fresh install of the plugin. Whenever I try to configure it against my airsonic server. It doesn't remember the settings. I fill it out and hit save, then it tries to connect to localhost everytime. It never even tries the settings I entered. If I open settings again it will be back to the default.

**Comment by jalabulajunx** [comment]
Hello, @ajmcateer - 

I have been running the above version of MusicBee for a while on an Airsonic server, and it remembers my settings every time. What plugin version are you using? Is it v2.14? If so, can you please try with v2.13 and report back if the settings are saved?

Do you see an error while saving the settings? The settings are saved in a file under AppData folder.

**Comment by midwan** [comment]
@ajmcateer 
Have you tried clicking on Apply first? Do you get an error message after that?
Apply will try to "ping" the server first and show a status message in MusicBee's status bar with the result (e.g. Subsonic server found). If it fails to connect, it will also mention that with a message box.

If it works with apply, clicking Save will also re-run those tests and finally save the settings - by default, the settings are saved under your username's AppData folder, where you should have full access (if not, you'd get another Windows error message about that).

Like @jalabulajunx said, which version of the plugin are you using? You can easily see that from within MusicBee's Plugins tab as well.

If it's v2.14, try using the previous version (v2.13) and see if that changes things?

**Comment by drsgoodall** [comment]
I've have the same issue with a new install (first time installing musicbee). v2.14 of the plugin does not save settings (either via save or apply). The connection error message always says localhost even if I have pressed "apply" and have a different host name in the settings. Replacing with v2.13 worked immediately.

**Comment by jalabulajunx** [comment]
@drsgoodall - Before I look further into this, can you please let me know if you tested the v2.13 as a fresh install as well? And, if you now replace v2.13 with v2.14 plugin - do you still see the same problem?

**Comment by drsgoodall** [comment]
I just copied the 2.13 version in place - existing settings etc left intact.
Updating in place to the v2.14 plugin - with the modified settings from v2.13  - it now seems to work. I.e. I can change the host name and it saves, updates and complains the server is not reachable. I can set it back to the working config too.

**Comment by chaddoncooper** [comment]
I think you need to select a transcode option, you can untick it afterwards, seems to have a null reference since adding the ability to change the transcoding bitrate otherwise.

**Comment by midwan** [comment]
This should be fixed with v2.15 now...
