### ISSUE TITLE
Disc Number not coming over from Subsonic

### ISSUE THREAD

**Issue by Cheeser12** [midwan/MB_SubSonic#42]
I'm having an issue where the disc numbers are not coming over from Subsonic. They are definitely valid tags in the files, as foobar2000 and the main Subsonic instance are processing them and sorting tracks correctly. Musicbee also picks them up when I play the music from my local directory.

I'm using v2.15 of the plugin, 3.1.6590 of MusicBee, and 6.1.3 of Subsonic

**Comment by jalabulajunx** [comment]
@Cheeser12 - I looked at the api documentation and also the dev forums of subsonic, and they do send the discnumber. Let me take a look at it over the weekend and get back.

**Comment by midwan** [comment]
I think we don't map that tag, let me see if I can fix that.

**Comment by midwan** [comment]
This is now implemented, it will be part of the next release.
