### ISSUE TITLE
No Password Field for Subsonic Plugin

### ISSUE THREAD

**Issue by Sealcove** [midwan/MB_SubSonic#43]
Greetings from Canada.

Hope you can assist with this recurring issue. I have installed, reinstalled the Subsonic Plugin for Music Bee and despite my best efforts, there is never any  password filed. Username is there but no/ no place to input the password. Any thoughts or suggestions would be greatly appreciated.

Thank you.

Scott

**Comment by midwan** [comment]
@Sealcove 
You mean the field doesn't show on the GUI?

**Comment by Sealcove** [comment]
Thanks for following up.  Yes, there is no field for PW in the GUI.

S

**Comment by midwan** [comment]
@Sealcove 
I cannot recreate this, and nobody else has reported something similar so far.
- What version of MusicBee are you running?
- How did you install it (meaning, did you get the installer, portable version, or from the Windows 10 Store)?
- What version of the plugin are you using?
- How did you install it? There's an option from within MusicBee (in Plugins, click on "Add Plugin") or you can manually copy the file in the proper folder.
- What screen resolution are you using?
- Are you using any High-DPI modes?

**Comment by Sealcove** [comment]
- What version of MusicBee are you running?
   -
   - How did you install it (meaning, did you get the installer, portable
   version, or from the Windows 10 Store)?
   - What version of the plugin are you using?
   - How did you install it? There's an option from within MusicBee (in
   Plugins, click on "Add Plugin") or you can manually copy the file in the
   proper folder.
   - What screen resolution are you using?
   - Are you using any High-DPI modes

**Comment by Sealcove** [comment]
- What version of MusicBee are you running?
   - 3.16.590
   - How did you install it (meaning, did you get the installer, portable
   version, or from the Windows 10 Store)?
   - Installer
   - What version of the plugin are you using?
   - latest v2.15.7z
   - How did you install it? There's an option from within MusicBee (in
   Plugins, click on "Add Plugin") or you can manually copy the file in the
   proper folder.
   - Been installling manually
   - What screen resolution are you using?
   - 2560 * 1440
   - Are you using any High-DPI modes
   - ???

**Comment by midwan** [comment]
@Sealcove 
What I meant by "high-dpi" modes is if you're using any interface scaling options in Windows (e.g. scaling to more than 100% is often used on laptop screens with high resolutions, to make things readable).

Does anything else in the MusicBee GUI look funny? E.g. fields overlapping?

Could you provide a screenshot of what you see?

**Comment by Sealcove** [comment]
Hi Dimitris,

Screenshot attached.  No high_dpi. Hope this helps. Thanks

Scott

**Comment by midwan** [comment]
Hm, the screenshot didn't come through I'm afraid...

**Comment by Sealcove** [comment]
Hmm..just checked .png file was attached. I will resend.

Scott

**Comment by Sealcove** [comment]
trying again .jpeg

Scott

**Comment by midwan** [comment]
Nope, sorry.
Try replying on the Github page directly and attaching the file there, maybe it doesn't work properly if you're just replying to the e-mail notification?

**Comment by Sealcove** [comment]
Done and thanks

S

**Comment by midwan** [comment]
@Sealcove 
Thanks!
The screenshot looks a bit strange to me, because it also shows a different list of plugins than the default. Did you install other plugins yourself?

For reference, here's how my installation looks like with only MB_Subsonic added:
![image](https://user-images.githubusercontent.com/3877365/42389666-babed2d6-8149-11e8-8f9c-cc908f491ea3.png)

Notice the "theater mode" options right below it? They don't show at all in your installation.

If you have installed other plugins indeed, could you try removing them one by one, to see if it makes any difference?

**Comment by Sealcove** [comment]
Thanks so much for assisting. Yup I have Android remote for MB. Works well.
Perhaps it is causing the issue. Uninstalled that plugin, problem persists.
So did a fresh install of MB from installer...installed your plugin and
voila, all is well and Subsonic accessing and working. Then reinstalled the
MB remote plugin and guess what, your PW field disappeared, lol. So
methinks we found the culprit.

Thanks so much for your great assistance and help.

Scott

**Comment by midwan** [comment]
@Sealcove 
Aha, great!
It shouldn't happen of course, but it seems to be related to that plugin?
I've followed the guidelines for positioning the preferences GUI elements, and it shouldn't interfere with other plugins. But we don't know what that other plugin has there, if it's doing something "funny" for example...

If you know the author of that plugin, I suggest you get in touch with them to let them know this is happening. It might be interfering with other plugins as well.
