### ISSUE TITLE
Is it possible for this to save ratings?

### ISSUE THREAD

**Issue by rogerizo** [midwan/MB_SubSonic#44]
Hi this is working fine but it wont save my ratings when i close and reopen musicbee is it possible to fix that please?

Thanks

**Comment by midwan** [comment]
Thanks for the suggestion.
I don't believe we're currently saving ratings, but I can look into that as a new feature.

**Comment by josepher44** [comment]
Strongly seconding this, ratings not getting pushed back to the server is the biggest missing feature preventing me from adopting this as my primary music setup.

**Comment by midwan** [comment]
We need some documentation from MusicBee's side to implement this, so I've asked Steven for that:
https://getmusicbee.com/forum/index.php?topic=1972.msg155207#msg155207

**Comment by midwan** [comment]
The "Star" tag is now mapped from SubSonic to MusicBee's "Love" tag, so it will show up correctly.
There's still no support for saving rating back into Subsonic.

**Comment by midwan** [comment]
We now have support for saving the Love/Star status and Rating of tracks, back to the SubSonic server.
However, I couldn't see where the track Rating shows in Subsonic? Only Album rating seems to be visible there...
