### ISSUE TITLE
Folder Listing

### ISSUE THREAD

**Issue by calandryll** [midwan/MB_SubSonic#46]
It appears with the most recent update to Subsonic (6.1.4) has broken how folders are displayed in MusicBee.  It looks like displayed folders in MB are based on Artists instead of folder name as it was in 6.1.3.  For example, I have a folder called Various Artists that is now spread throughout and none of the files in those folders is playable via MB. 

![error](https://user-images.githubusercontent.com/2163644/48482037-89c55600-e7dd-11e8-99cb-a2787b1da880.png)

These files are played fine in a browser.

**Comment by midwan** [comment]
@calandryll 
Thanks for reporting this. I don't have much free time at the moment, so it will take me a while to get into it, but I'll update this Issue with more news once I do.

**Comment by calandryll** [comment]
Thanks for looking into it.  It seems to be some kind of maintenance update to Subsonic.  At this point I may migrate to Airsonic.

**Comment by andocromn** [comment]
its probably also worth noting that I'm behind on MB and the plugin versions
MB v 3.0.6335
Plugin v 2.11.0.0
I'll test on current and post my results

**Comment by midwan** [comment]
@calandryll 
I'm trying to recreate this with the latest Subsonic server (I can't so far).
Could you give me some more details on those tracks?

Is the Various Artists an ID3Tag, and if so which one? Artist, Album artist, or other?
And I assume they are located in different folders, and only the Artist tag matches between them?

**Comment by calandryll** [comment]
The way I have Various Artists setup, usually for soundtracks, etc. Is a folder called Various Artists and then in the tags under artist will be the artist and under artist album is usually various artists.

I moved away from Subsonic to Airsonic pretty much right after this error and haven't had any issues yet.

**Comment by midwan** [comment]
It looks like it's working in the current Subsonic version also, so I'm closing this unless we discover that's not the case.
