### ISSUE TITLE
Retrieving song ratings don't work

### ISSUE THREAD

**Issue by ArnaudB88** [midwan/MB_SubSonic#49]
When opening a subsonic/airsonic server and select a playlist, the song ratings are not loaded.
Saving a rating works correctly. I verified this by setting song ratings in MusicBee and refreshing the playlist in my Dsub Android app.
When changing subsonic playlists, the ratings are also lost.

**Comment by midwan** [comment]
@ArnaudB88 
I think there was some limitation that caused this, but I have to refresh my memory.
Let me look into it again and get back to you, if it's possible to do then I might have missed it and we'll get it sorted. :)

**Comment by midwan** [comment]
@ArnaudB88 
There seems to be a bug in the MusicBee interface, which doesn't really respect the Rating you set on a track. It always reports back a rating of "0" in that event, so even though it shows the right Rating on screen, only "0" (=no rating) is sent to the Server. Which of course means that when you refresh the list of tracks, the rating doesn't exist anymore.

I'll report this to Steven of MusicBee, in case he hasn't noticed.

**Comment by midwan** [comment]
@ArnaudB88 
I spoke a little too soon regarding the "Love" status. It does work for Setting it to the server, and it does retrieve it correctly, but only after restarting MusicBee. It seems that the call to "GetTags" only happens initially, but not when you Refresh.

I'll look into that in the meantime.

**Comment by midwan** [comment]
@ArnaudB88 The refresh problem is fixed now, so if you click on a folder you will get the updated files it contains (including changes in the Rating/Star setting).
The Rating problem remains however, and it's coming from MusicBee from what I can see. I've reported it to Steven.

**Comment by midwan** [comment]
@ArnaudB88 
Published v2.28 with the above bugfix, feel free to test it and report back:
https://github.com/midwan/MB_SubSonic/releases/latest

**Comment by midwan** [comment]
The bug in MB, which always seems to return "0" for Ratings, has been reported to Steven here: https://getmusicbee.com/forum/index.php?topic=1972.new;topicseen

However, I'm not sure when/if this will be fixed. Until it is, there's nothing I can do from my side regarding this case. :-/
