### ISSUE TITLE
Improve search/indexing

### ISSUE THREAD

**Issue by nightah** [midwan/MB_SubSonic#5]
So I have quite a large Music collection being served out of Subsonic ~4280 folders.

When I initially expand my Music collection I can see the MusicBee plugin subsequently performing a 'GET /subsonic/rest/getMusicDirectory.view' on every single directory which takes some time.
During the scanning period nothing is actually populated in the MusicBee window to search from, you have to browse to each individual folder to be presented with the contents for search.
Normally this wouldn't be a problem but if you shutdown and open MusicBee it performs the above from scratch.

Could we perhaps write a local index and validate that in the background on launch and update accordingly, or perhaps there might be a better way to handle this?

**Comment by midwan** [comment]
There is already a local cache file, which is populated from the server. Once the contents are fetched, they are saved there and it won't fetch them again - unless of course the operation was cancelled or the server has new content.

I agree that we should look into improving this, but AFAIK the Subsonic API does not provide a function to get ALL the content in one go. It will only show content for a specific folder id. Alternatively, it can get content per ID3 tags.

**Comment by nightah** [comment]
I was thinking about this a little more, in absence of the ability to get all content in one go could we use the ifModifiedSince parameter for the getIndexes call? Would this mean we only need to call getMusicDirectory on newly added files?

Perhaps also allowing us to force a refresh via a button in the plugin window too, because right now I need to close MusicBee, browse to a new folder to initiate a refresh which will result in a scan for every single folder.

Happy to put the second request in a new issue if you prefer, please advise.

**Comment by midwan** [comment]
Regarding the Refresh, doesn't it work for you if you just hit F5 when having a subsonic node selected? It should refresh at that point without the need to restart anything. And if you already have finished one complete caching, it should also be quite fast as well.

There is a mechanism to detect modified changes and only fetch those during the scan. But it won't help with the initial slow scan, at least the way it's done now (recursively for each folder).

Subsonic offers an alternative way of fetching information, besides the file/folder tree method. It can also serve them as Tags, so you can request and get a list of all Artists for example. I think it's worth exploring that direction to see how much it would benefit us - I have a feeling it would be faster.

In any case, I agree that this is an area that should be improved, so I'll mark this issue as such.

**Comment by midwan** [comment]
I've just pushed out a new beta version fixing issue #9 here: 
https://github.com/midwan/MB_SubSonic/releases/tag/v2.5-beta

It should also improve speed among other things, would you mind giving it a try and let me know how it goes for you?

**Comment by nightah** [comment]
Can do, I've just pulled it down - will test and report my findings.

**Comment by nightah** [comment]
Seems better on the aggregation but playing is super slow now because it waits until the song has finished downloading completely before beginning. So it isn't streaming anymore.

**Comment by midwan** [comment]
Thanks for reporting that. Could you try with the below release and let me know if this is still an issue?
https://github.com/midwan/MB_SubSonic/releases/tag/v2.6-beta

**Comment by nightah** [comment]
Still looks like it isn't streaming, and waiting until the file is completed.
Let me know if need more information I can measure time diffs between the versions and such if required.

**Comment by midwan** [comment]
OK, thanks for reporting. I think I know where this is coming from, so it will be fixed in the next beta update.

I'll let you know when a new version is ready so you can give it another try, here.

**Comment by midwan** [comment]
Meanwhile, this issue can be closed - we can open a separate one for the streaming problem.
