### ISSUE TITLE
Are you planning to support API search?

### ISSUE THREAD

**Issue by tesshucom** [midwan/MB_SubSonic#50]
#### problem
At the moment, the search seems to refer to the local object instead of the API search method.

#### solution
The preferred solution is to search using the Subsonic API's search method rather than referencing a local object.
(In other words ... search is to have a plug-in mechanism design. Design changes of the main program will be required)

In essence, searching for objects on a Subsonic server relies on server-specific logic.
 - Speaking of implementation, the results may vary depending on the Subsonic version.
 - There will also be servers with special search implementations.
___
This is a question rather than a request.
 - Is the current implementation tentative and will be fixed in the future?
 - Is this a functional limitation of MusicBee and no action taken?

**Comment by midwan** [comment]
@tesshucom 
To implement this, we'd have to go through the Interface that MusicBee provides. I haven't seen support for such a function in there so far, but I can ask Steven just in case.

I believe this might affect how MusicBee functions internally also, as it seems to be oriented towards 1) building a local database for the media files found and 2) doing the searches locally in there afterwards.

**Comment by tesshucom** [comment]
Thank you for your response.

> I believe this might affect how MusicBee functions internally also, as it seems to be oriented towards 1) building a local database for the media files found and 2) doing the searches locally in there afterwards.

You're right. And it is imagined to be painful.
Heavy Subsonic users may have similar naive questions as I do.
So please consider this as a light question rather than a strong demand.

**Comment by midwan** [comment]
Closing this, as there's nothing I can do until MusicBee implements support for it
