### ISSUE TITLE
The filename was not found in the path

### ISSUE THREAD

**Issue by lachlan-00** [midwan/MB_SubSonic#52]
What file and what path?
![image](https://user-images.githubusercontent.com/1305249/67154147-1d7e9b00-f33a-11e9-94af-e3a166334dd3.png)

**Comment by midwan** [comment]
Sorry, I know the message is not very clear there (will fix it in the next update).
It's referring to the Cache file, I guess you tried to delete it?
If it doesn't exist, you'll get this message as a warning (it's OK if it doesn't exist of course, just letting you know).

**Comment by lachlan-00** [comment]
the new message is much clearer!
