### ISSUE TITLE
Background task keeps fetching even after shifting focus

### ISSUE THREAD

**Issue by Koenvh1** [midwan/MB_SubSonic#56]
I noticed that when PreCacheAll is set to true, it will fetch the current level plus all levels below it. That is intended, however, once the focus is shifted from the top level to another level (such as a sublevel), and it was not finished fetching yet, then it will keep fetching even though the result will no longer be used. In my case, this means that I am suddenly sending a couple hundred requests to my server (or actually to Astiga) that will not be used, which seems a bit of a waste.

Now to counter that, I added a unique ID to the start of each task, and passed that along with the task. As soon as a new task is started, a new ID is generated, and the old task will abort. Like this:
```csharp
private static string _taskId;
```

```csharp
var uniqueId = Guid.NewGuid().ToString("N");
_taskId = uniqueId;
GetFolderFiles(path.Substring(0, path.IndexOf(@"\", StringComparison.Ordinal)), folderId, files, uniqueId);
```

```csharp
private static void GetFolderFiles(string baseFolderName, string folderId, ICollection<KeyValuePair<byte, string>[]> files, string taskId)
{
    if (taskId != _taskId) return;
```
From my initial testing it seems to work fine. However, am I overlooking something that would break this way? I have only tested it against Astiga, not against the original Subsonic server, but I think it should work the same. I would create a pull request, but I have been experimenting around with some other things as well, and it is a bit difficult to separate those changes now.

**Comment by midwan** [comment]
@Koenvh1 
Thanks! I'll test this, it looks like a good approach (and that area generally needs some extra love for sure).

**Comment by midwan** [comment]
This should be fixed with the new release: https://github.com/midwan/MB_SubSonic/releases/tag/v2.30
I've removed pre-caching altogether, as it wasn't really worth the trouble it caused. Instead, we load files/folders on-demand now, which should be faster for most people.
