### ISSUE TITLE
Ping against Ampache returns "Error retrieving response"

### ISSUE THREAD

**Issue by StephenAtty** [midwan/MB_SubSonic#58]
**Describe the bug**
Running against Ampache 4.3.0 returns an error when trying to ping the server

**To Reproduce**
1. Go to MusicBee plugin configuration
2. set up server to point to ampache server
3. click on ping

**Expected behavior**
I'd expect ping to work. Subsonic clients on my phone do not have this problem

**Screenshots**

![image](https://user-images.githubusercontent.com/251449/111033540-af90b300-8409-11eb-9edb-99d8c78dfa93.png)

**Additional context**
Apache logs show:

`[13/Mar/2021:14:36:25 +0000] "GET /rest/ping?u=steve&t=2e42fb6bc9e857f616e107c2e79c6390&s=09b00b97625e54911934&v=1.13.0&c=MusicBee HTTP/1.1" 404 281`

which suggests that the wrong url is being called - shouldn't this be ping.view

Ultrasonic makes the following call for ping:

`[13/Mar/2021:14:41:51 +0000] "GET /rest/ping.view?u=steve&c=Ultrasonic&f=json&v=1.7.0&p=enc:46616C636F6E31323334 HTTP/2.0" 200 84 "-" "okhttp/3.10.0"`

**Comment by midwan** [comment]
Seems like different implementations of Subsonic-compatible APIs have some changes in the details as well. It worked with just `ping` on other implementations I was testing recently. :)
I'll get it fixed, thanks for reporting it!

**Comment by midwan** [comment]
Please test with https://github.com/midwan/MB_SubSonic/releases/tag/v2.31 and let me know if there's still a problem with your server.

**Comment by StephenAtty** [comment]
That worked - it connected and pinged OK.

there seem to be problems with browsing the server and getting it to play music - but I suspect that might be MusicBee rather than your plugin.
