### ISSUE TITLE
Use MB_susbsonic with proxy

### ISSUE THREAD

**Issue by blattes86** [midwan/MB_SubSonic#6]
Hi,
When i want use mb_subsonic I have this message: 

> 
Error : The remote server returned an error : (407) Proxy Authentication Required

The proxy configuration is correct in settings ( radio OK, download covers OK ...)

thank you in advance for your help

**Comment by midwan** [comment]
Which proxy do you use?
Does it work if you don't use a Proxy (if you have that possibility)?
Are you using the latest version of MusicBee (currently v3)?

**Comment by midwan** [comment]
No feedback received, so this is getting closed for now.
