### ISSUE TITLE
Library not showing in the subsonic node

### ISSUE THREAD

**Issue by zachminot** [midwan/MB_SubSonic#8]
Anyone still active here? I can go into a lot more detail if need be, just wanna make sure someone is on the other end!

**Comment by midwan** [comment]
Yes, I am here. :) Please describe your problem in detail, including versions of MusicBee, operating system, Subsonic server used.

**Comment by zachminot** [comment]
MusicBee Version: 2.5.5804
Subsonic Version: 5.3 (build 4569) (I'm also paying for the premium version)
Plugin Version: subsonic v2
OS: Windows 10 Pro 

I can't get my music to show up under the Subsonic icon in the computer node. 
I have tested this for a small folder with 2 sub folders and a couple of songs so I know its not the size of my collection that's causing the problem. I will play around with it, I have gotten the music to show up before, but only by drilling down to each sub-folder. 

It would be great if the music showed up when you click on the subsonic icon, without having to drill down to each album if possible. Thank you for your time!

![image](https://cloud.githubusercontent.com/assets/10821996/17079213/21b54100-50d7-11e6-86aa-988cb3302df9.png)


![image](https://cloud.githubusercontent.com/assets/10821996/17079218/39fde848-50d7-11e6-9f47-cd20cf77ed04.png)

![image](https://cloud.githubusercontent.com/assets/10821996/17079224/66530982-50d7-11e6-9dab-7aa98d2500d4.png)


![image](https://cloud.githubusercontent.com/assets/10821996/17079225/6efa0d92-50d7-11e6-8305-dbd5f5ea4e56.png)

**Comment by zachminot** [comment]
Also, I've left it running for days, and the list still has not populated on the master subsonic node. Thanks again.

**Comment by midwan** [comment]
Thanks for the info, I'll setup an environment to try and recreate this problem and see where we are.

**Comment by midwan** [comment]
Hmm, I can't see to get the same problem in my tests. There must be something I have differently setup somewhere.

<img width="1110" alt="musicbee" src="https://cloud.githubusercontent.com/assets/3877365/17221501/5e239102-54f4-11e6-9be1-9550b1c10384.png">

Any chance you could setup a test account for me on your server and e-mail me the details, so I can test with those? Perhaps it's something I can recreate it that way, and if so it would help a lot in finding a solution.

**Comment by zachminot** [comment]
Surely, what email should I send it to?

**Comment by zachminot** [comment]
I appreciate your time Dimitris! Here's my teamviewer credentials feel free
to log in and do whatever you need to as long as its between 10am-12pm
Eastern Standard Time (Other my computer is sleeping).
Let me know, thank you!

TeamViewer id:
109 705 789
Teamviewer pass:
t932pc

**Comment by midwan** [comment]
I've updated your comment to mask out the connection details, as this is a public post... :)

Meanwhile, I've just finished working on issue #9 and pushed out a new beta release here:
https://github.com/midwan/MB_SubSonic/releases/tag/v2.5-beta

Could you please give it a try and see if it solves the problem for you?

**Comment by zachminot** [comment]
Thank you Midwan!!! I can now see my full subsonic library when I click on the subsonic icon. I do get occasional "directory not found" error messages when clicking on folders in the computer node explorer, but usually clicking the folder again results in the selected folder showing up. Thanks again! This plugin combined with MusicBee is definitely the most effective way to share a media library. I can have my subsonic server running from my Raspberry Pi and can access it AND manage tags with any computer on the network that has MusicBee and this plugin.

**Comment by midwan** [comment]
Happy to see that it works for you! :)
I am aware of the "Directory not found" problem, so I hope to have this resolved soon in another version update. Meanwhile I guess we can close this issue then.
